import React, { useEffect, useState } from 'react';

const API_URL = import.meta.env.VITE_API_URL || (import.meta.env.PROD ? '/api' : 'http://localhost:5000/api');
const blank = { slug: '', title: '', author: 'Dr Sweta Adatia', category: 'general', thumbnail_url: '', course_url: '', original_price: '', sale_price: '', currency: 'INR', sort_order: 0, is_free: false, is_visible: true };
export const serializeCourse = (course) => ({ ...course, original_price: course.original_price === '' ? null : course.original_price, sale_price: course.is_free || course.sale_price === '' ? null : course.sale_price, is_free: Boolean(course.is_free), is_visible: Boolean(course.is_visible) });

export default function BrainCoursesManagement() {
  const [courses, setCourses] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const headers = () => ({ 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('authToken')}` });
  const load = async () => { setLoading(true); try { const r = await fetch(`${API_URL}/brain-courses/admin`, { headers: headers() }); const b = await r.json(); if (!r.ok) throw new Error(b.error); setCourses(b.courses || []); } catch (e) { setError(e.message || 'Could not load courses'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const save = async (e) => { e.preventDefault(); setSaving(true); setError(''); try { const r = await fetch(`${API_URL}/brain-courses/admin${editing ? `/${editing}` : ''}`, { method: editing ? 'PATCH' : 'POST', headers: headers(), body: JSON.stringify(serializeCourse(form)) }); const b = await r.json(); if (!r.ok) throw new Error(b.error); setForm(blank); setEditing(null); await load(); } catch (err) { setError(err.message || 'Could not save course'); } finally { setSaving(false); } };
  const edit = (course) => { setEditing(course.id); setForm({ ...course, original_price: course.original_price ?? '', sale_price: course.sale_price ?? '' }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const field = (key, label, type = 'text') => <label className="block text-sm font-medium text-gray-700">{label}<input required={['slug','title','author','category','course_url'].includes(key)} type={type} value={form[key] ?? ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full rounded border p-2" /></label>;
  if (loading) return <div className="animate-pulse space-y-3"><div className="h-10 rounded bg-gray-100"/><div className="h-32 rounded bg-gray-100"/></div>;
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold">Patient Brain Courses</h2><p className="text-sm text-gray-500">Changes appear automatically in the patient portal.</p></div>{error && <p className="rounded bg-red-50 p-3 text-red-700">{error}</p>}<form onSubmit={save} className="grid grid-cols-1 gap-3 rounded-xl border bg-white p-5 md:grid-cols-2">{field('slug','Slug')}{field('title','Title')}{field('author','Author')}{field('category','Category')}{field('thumbnail_url','Thumbnail URL')}{field('course_url','Course URL')}{field('original_price','Original price','number')}{!form.is_free && field('sale_price','Sale price','number')}{field('currency','Currency')}{field('sort_order','Sort order','number')}<label className="flex items-center gap-2"><input type="checkbox" checked={form.is_free} onChange={(e) => setForm({ ...form, is_free: e.target.checked, sale_price: e.target.checked ? '' : form.sale_price })}/>Free course</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.is_visible} onChange={(e) => setForm({ ...form, is_visible: e.target.checked })}/>Visible to patients</label><div className="md:col-span-2 flex gap-3"><button disabled={saving} className="rounded bg-[#323956] px-4 py-2 text-white">{saving ? 'Saving…' : editing ? 'Save changes' : 'Add course'}</button>{editing && <button type="button" onClick={() => { setForm(blank); setEditing(null); }} className="rounded border px-4 py-2">Cancel</button>}</div></form><div className="overflow-hidden rounded-xl border bg-white">{courses.length ? courses.map((course) => <div key={course.id} className="flex items-center justify-between border-b p-4 last:border-0"><div><p className="font-semibold">{course.title}</p><p className="text-sm text-gray-500">{course.is_free ? 'Free' : `${course.currency} ${course.sale_price}`} · {course.is_visible ? 'Visible' : 'Hidden'}</p></div><button onClick={() => edit(course)} className="text-blue-600">Edit</button></div>) : <p className="p-6 text-gray-500">No courses yet.</p>}</div></div>;
}
